name: mongodb_by_rest_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

# package local que não será publicado
publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.5
  http: ^1.2.2
  convert_json:
    git:
      url: https://github.com/Suebersson/convert_json.git

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
